### ISSUE TITLE
Blending Mode

### ISSUE THREAD

**Issue by paulvill** [cdanewschool/vr_embryo#1]
Find out about blending mode in order to get rid of the black background

<https://threejs.org/examples/webgl_materials_blending.html>

**Comment by defenestrated** [comment]
fixed! [this example helped](https://threejs.org/docs/scenes/material-browser.html#MeshBasicMaterial)

(in the [data-model-interaction branch](https://github.com/cdanewschool/vr_tests/tree/data-model-and-interaction))

the trick is doing `alphaMap` instead of plain `map` – this has the added bonus of letting us tint the images
